version: '2'
services:
  dipalza-fastapi-server:
    build:
      context: .
      dockerfile: dipalza.Dockerfile
    image: dipalzaimage:1.0
    ports:
      - "8099:80"
    volumes:
      - .:/app
    
volumes:
  app:
